FROM ubuntu:latest

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install \
    # Pakages
    g++-10 \
    build-essential \
    cmake \
    ninja-build \
    clang-format \
    git \
    cpputest
